services:
  fluent-bit-authService:
    image: fluent/fluent-bit:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2022:2022"
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./parsers.conf:/fluent-bit/etc/parsers.conf
      - ../app/logs:/app/logs
    restart: unless-stopped
